services:
  zbx-agent-1:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zbx-agent-1
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_ACTIVE: zabbix-server
      ZBX_HOSTNAME: agent-1
      ZBX_METADATA: agent
    restart: unless-stopped
    networks: [zabbix_default]

  zbx-agent-2:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zbx-agent-2
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_ACTIVE: zabbix-server
      ZBX_HOSTNAME: agent-2
      ZBX_METADATA: agent
    restart: unless-stopped
    networks: [zabbix_default]

  zbx-agent-3:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zbx-agent-3
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_ACTIVE: zabbix-server
      ZBX_HOSTNAME: agent-3
      ZBX_METADATA: agent
    restart: unless-stopped
    networks: [zabbix_default]

  zbx-agent-4:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zbx-agent-4
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_ACTIVE: zabbix-server
      ZBX_HOSTNAME: agent-4
      ZBX_METADATA: agent
    restart: unless-stopped
    networks: [zabbix_default]

networks:
  zabbix_default:
    external: true
