services:
  zbx-agent-autoscale:
    image: zabbix/zabbix-agent2:alpine-latest
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST:-zabbix-server}
      ZBX_SERVER_ACTIVE: ${ZBX_SERVER_ACTIVE:-zabbix-server}
      ZBX_HOSTNAMEITEM: system.hostname
      ZBX_METADATA: ${ZBX_METADATA_AUTOSCALE:-autoscale-linux}
    restart: unless-stopped
    networks:
      - zabbix_default

networks:
  zabbix_default:
    external: true
